version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: "./docker/web/Dockerfile"
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./docker/web/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
